version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: boats_db
      POSTGRES_USER: testusr
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  boats:
    container_name: boats
    build: .
    ports:
      - "9876:9876"
    depends_on:
      - db
    links:
      - db
